#!/bin/bash
echo -e "\e[32m====================================${0}====================================\e[0m"
cd ~ && mkdir 3rd && cd 3rd
git clone https://github.com/Photin1a/clash_linux.git && cd clash_linux
tar -xvf cfw.tar.xz
rm cfw.tar.xzj
