#!/bin/bash
sudo apt update
sudo apt upgrade
sudo apt autoremove

chmod 777 *
./clash_linux_install 
./source_and_ros_install 
# ./sougou_install 
./vscode_install 
./obsidian_install
./vim_install
./todesk_install 
./qt5.15.2_install
