#!/bin/bash
# 先卸载掉fcitx，及其所有相关的软件
echo -e "\e[32m====================================${0}====================================\e[0m"

sudo apt -y --purge remove *fcitx*
sudo apt clean *fcitx*

sudo apt install -y fcitx

cd ~/Downloads && sudo apt install -y wget 
wget https://ime-sec.gtimg.com/202403071420/22bada687d64a1ed174182e4fdbc9f84/pc/dl/gzindex/1680521603/sogoupinyin_4.2.1.145_amd64.deb
sudo dpkg -i sogoupinyin_4.2.1.145_amd64.deb
