#!/bin/bash
echo -e "\e[32m====================================${0}====================================\e[0m"

sudo apt install -y git 
git clone https://github.com/Photin1a/vimrc.git &&cd ./vimrc && chmod 777 vim_install.sh &&  ./vim_install.sh
